### ISSUE TITLE
Free Selection mode is no longer necessary?

### ISSUE THREAD

**Issue by uiureo** [gyazo/gyazo-chrome-extension#131]
With the current version of Gyazo native client, you can capture screenshots with title and url.
So now, use cases of Free Selection mode are rare.

@rakusai @pastak How do you think?

**Comment by pastak** [comment]
I think "Free Selection mode" is useful for capturing a webpage is larger than window's height

**Comment by uiureo** [comment]
> I think "Free Selection mode" is useful for capturing a webpage is larger than window's height

Agree. But I've never seen cases like that.
In most cases, I use Whole Page capture mode.

Do you really use Free Selection mode?

**Comment by drobune** [comment]
Excuse me for cutting in.
My default setting is Free Selection mode.

**Comment by hiroshi** [comment]
I think "free selection" may be useful for platforms without Gyazo clients.
