### ISSUE TITLE
Show title and the domain name in the saved popup

### ISSUE THREAD

**Issue by rakusai** [gyazo/gyazo-chrome-extension#159]
this design gives users more confirmation that Gyazo is capturing title and the url!

[![Gyazo](https://bot.gyazo.com/e679d17693fe4b2270499f19825be040.png)](https://gyazo.com/e679d17693fe4b2270499f19825be040)

**Comment by pastak** [comment]
Good Idea

**Comment by yoshiharatakeru** [comment]
Good 👍 
It can introduce bookmark-like use case
