### ISSUE TITLE
Enter the white line.

### ISSUE THREAD

**Issue by k725** [gyazo/gyazo-chrome-extension#17]
Check the photos.

最大化してないChromeでページ全体のキャプチャを行うと白い線が入ります。
似たような機能を持つ[他の](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl)拡張機能では発生しなかったのでバグという形で報告させて頂きます。

テストページ : [Steam: Game and Player Statistics](http://store.steampowered.com/stats/)

---------

Window
![WIndow](http://pic.hoshinoa.me/6xgIb4.png)

Maximize window
![Full Window](http://pic.hoshinoa.me/PzlURI.png)

**Comment by pastak** [comment]
@k725 遅くなりましたが報告いただいていたバグについて修正を master に merge しましたのでご確認ください。

報告ありがとうございました
