### ISSUE TITLE
capture wrong area with retina

### ISSUE THREAD

**Issue by hiroshi** [gyazo/gyazo-chrome-extension#171]
Try to do "free selection" this rectangle.
[![https://gyazo.com/c97e56cd8805b80c3e636faf4f61e533](https://i.gyazo.com/c97e56cd8805b80c3e636faf4f61e533.png)](https://gyazo.com/c97e56cd8805b80c3e636faf4f61e533)
But I got this (white left side and transparent color right side).
[![https://gyazo.com/b8d4f33f2e5d9efaba57435a77307193](https://i.gyazo.com/b8d4f33f2e5d9efaba57435a77307193.png)](https://gyazo.com/b8d4f33f2e5d9efaba57435a77307193)

**Comment by pastak** [comment]
I cannot reproduce this issue.

Is your display mode retina? plz more info

**Comment by pastak** [comment]
I have reproduced on retina display
