### ISSUE TITLE
Gray lines will be shown for each page

### ISSUE THREAD

**Issue by rakusai** [gyazo/gyazo-chrome-extension#21]
http://gyazo.com/5ab6e31688e83ce388ce00dec245c6b8

win7 chrome

**Comment by pastak** [comment]
I found reason: It calculates `window.outerWidth / window.innerWidth`  to get browser zoom setting. chrome is not maxium, `window.outerWidth` contains window's border. So, calculated value is bigger than actual zoom setting.
