### ISSUE TITLE
Gyazo captures its own shadow

### ISSUE THREAD

**Issue by alfonsojon** [gyazo/gyazo-chrome-extension#53]
Self descriptive; see the photo.
![](https://i.gyazo.com/0af166adab29788a230f06c76c3406a8.png)

**Comment by pastak** [comment]
@alfonsojon Sorry for this issue.

We have known it and work to fix it.

Please wait for next release. :bow:

**Comment by alfonsojon** [comment]
@pastak Thank you

**Comment by pastak** [comment]
@alfonsojon We release new version. We believe fixed it. please try it :smile:

**Comment by alfonsojon** [comment]
!(New version works!)
[https://i.gyazo.com/f142bf3c174c9d7e8e65be310c717bc8.png]
