### ISSUE TITLE
Whole page screenshots are effected in the top right of the screen

### ISSUE THREAD

**Issue by RanSolo** [gyazo/gyazo-chrome-extension#81]
Here is my page (in local rails environment) before.  

<img width="439" alt="screenshot 2015-10-05 17 20 35" src="https://cloud.githubusercontent.com/assets/6284142/10295380/f9b81538-6b85-11e5-9bd1-88e684c5d85a.png">

I bring up Gyazo chrome extention and click whole page...

 <img width="606" alt="screenshot 2015-10-05 17 21 04" src="https://cloud.githubusercontent.com/assets/6284142/10295379/f9b75d6e-6b85-11e5-952a-fc7c86dd0aea.png">

Here is resulting Gyazo Screenshot screenshot, notice (where the Gyazo extension was located maybe?) at the top right of the page, the gear that was there is shifted in.

[![Gyazo](https://i.gyazo.com/94ad0334f613e6d90d6950be02e3938e.png)](https://gyazo.com/94ad0334f613e6d90d6950be02e3938e)
 
It remains changed on my screen as well
<img width="458" alt="screenshot 2015-10-05 17 30 04" src="https://cloud.githubusercontent.com/assets/6284142/10295529/d3aaed9c-6b86-11e5-9501-0a7b2b195466.png">

When I refresh page it goes back to normal.
<img width="623" alt="screenshot 2015-10-05 17 30 19" src="https://cloud.githubusercontent.com/assets/6284142/10295535/dc2eaf9e-6b86-11e5-9ddd-7fb50f05231c.png">

**Comment by pastak** [comment]
@RanSolo Thanks for your report :smile: 

Gyazo Extension changes HTMLElement `position: fixed` to `positon: absolute` and add `.gyazo-whole-capture-onetime-absolute` before capturing and restores css `positon:fixed` and remove css class after capturing.

So, I think it failed to restore. Please check that does element have `position:absolute`.

Sorry It's bug I want to fix but I can't reproduce... :cry:
