### ISSUE TITLE
Can't upload bmp image

### ISSUE THREAD

**Issue by pastak** [gyazo/gyazo-chrome-extension#86]
It can't upload bmp image by context menu.

**Comment by pastak** [comment]
It should convert bmp to png

**Comment by rakusai** [comment]
I don't think we should support bmp.

**Comment by hiroshi** [comment]
Just curious to know, when do you want to upload bmp? Are there any popular web site which use bmp these day?

**Comment by uiureo** [comment]
> I don't think we should support bmp.

I agree.
People won't use bmp in websites anymore. And it's very rare when we see bmp to capture.
Even if you can't capture bmp by right click, you can use selection capture or a native client.

So I think this is not our priority.

**Comment by uiureo** [comment]
Reopen if you find critical use case

**Comment by uiureo** [comment]
It might be better if it says a helpful message 'This image format is not supported. Try selection capture.'
