### ISSUE TITLE
Sometimes "capture this image" does't work 

### ISSUE THREAD

**Issue by drobune** [gyazo/gyazo-chrome-extension#89]
found on google image search
[![https://gyazo.com/becf0c49e6ee0487055f0203ca410384](https://i.gyazo.com/becf0c49e6ee0487055f0203ca410384.gif)](https://gyazo.com/becf0c49e6ee0487055f0203ca410384)

**Comment by uiureo** [comment]
It might be a data url?

**Comment by drobune** [comment]
yeah!
[![https://nota.gyazo.com/d510841ca7a956f825a67edfc34ea28f](https://t.gyazo.com/teams/nota/d510841ca7a956f825a67edfc34ea28f.png)](https://nota.gyazo.com/d510841ca7a956f825a67edfc34ea28f)

**Comment by rakusai** [comment]
fixed: https://github.com/gyazo/gyazo-chrome-extension/pull/108
