### ISSUE TITLE
Strategy: Upload image server-side app doesn't support format or dataURL

### ISSUE THREAD

**Issue by pastak** [gyazo/gyazo-chrome-extension#90]
ref: https://github.com/gyazo/gyazo-chrome-extension/issues/89
ref: https://github.com/gyazo/gyazo-chrome-extension/issues/86

- If src is dataURL
  - dataURL is match `image/jpg` or `image/png` or `image/gif`
  - upload it to gyazo directly
- if src is image but not jpg, png or gif format
  - convert it to png via canvas
  - upload

**Comment by drobune** [comment]
:+1:

**Comment by rakusai** [comment]
I think we don't have to support bmp. they are too rare.

**Comment by drobune** [comment]
i want to upload webm :movie_camera:
