### ISSUE TITLE
Can't gyazo elements and whole page on slack channels.

### ISSUE THREAD

**Issue by drobune** [gyazo/gyazo-chrome-extension#92]
### elements case 
[![https://gyazo.com/ef558d383fe541051a03347a5835b061](https://i.gyazo.com/ef558d383fe541051a03347a5835b061.gif)](https://gyazo.com/ef558d383fe541051a03347a5835b061)

- not  uploading
- no error message in background console

### wholepage case
[![https://gyazo.com/bb38cefecb0ed309e45355185dd2e0e8](https://i.gyazo.com/bb38cefecb0ed309e45355185dd2e0e8.gif)](https://gyazo.com/bb38cefecb0ed309e45355185dd2e0e8)

- window is broken
- no error message in background console

**Comment by pastak** [comment]
Maybe solbed by https://github.com/gyazo/gyazo-chrome-extension/pull/93 ?

**Comment by drobune** [comment]
ya!
